### ISSUE TITLE
Meta Hands profiles are missing "Spatial Pointer" interaction profiles "by default"

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#13]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

After importing and configuring the Meta platform and enabling it's configuration, the Spatial Pointer interaction profile is not configured.  This causes errors when hands are detected at runtime.

Likely caused to the SDK update

## To Reproduce

1. Create Project
2. Import Core and Meta platforms via OpenUPM
3. Ensure Meta configuration is applied to the Mixed Reality Configuration
4. Run project via Meta Link and switch from controllers to hands
5. See errors

## Your Setup

- **Operating System:**

    - [ ] Windows
    - [ ] MacOs
    - [ ] Linux
    - [ ] Other

- **Target Platforms:**

    - [ ] WindowsXR
    - [ ] HoloLens
    - [X] Meta Quest
    - [ ] Pico
    - [ ] Other (please specify)

- **Unity Version:** 
 

 - 2020.3.30f

- **Packages**
    - [X] com.realitytoolkit.core 1.0.0.Preview.2 
    - [X] com.realitytoolkit.metaplatform1.0.0.Preview.2
